import tkinter as tk
from tkinter import ttk

from data.elements_info import elements_info
from data.elements_position import elements_position

import utils.search as search


class PeriodicTable(tk.Frame):
    def __init__(self, parent):
        tk.Frame.__init__(self, parent)
        self.parent = parent
        self.active_property = 'Atomic Number'
        self.search = search.Search(self.parent)
        self.search_symbol = self.search.search_symbol
        self.search_atomic_number = self.search.search_atomic_number
        self.elements = []
        self.create_periodic_table()

    def create_periodic_table(self):
        root = self.parent

        self.configure_styles()

        for element_position in elements_position:
            el = ttk.Button(self.parent, text=(self.get_element_text(element_position)),
                            style=element_position['style'], command=self.create_command((element_position['symbol'])))
            el.place(x=element_position['x'], y=element_position['y'])
            self.elements.append(el)

        # el = ttk.Button(self.parent, text=(elements_info['H']['Symbol'] + '\n' + elements_info['H'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('1'))
        # el.place(x=5,y=100)
        # el = ttk.Button(self.parent, text=(elements_info['He']['Symbol'] + '\n' + elements_info['He'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('2'))
        # el.place(x=685, y=100)
        # el = ttk.Button(self.parent, text=(elements_info['Li']['Symbol'] + '\n' + elements_info['Li'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('3'))
        # el.place(x=5, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['Be']['Symbol'] + '\n' + elements_info['Be'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('4'))
        # el.place(x=45, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['B']['Symbol'] + '\n' + elements_info['B'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('5'))
        # el.place(x=485, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['C']['Symbol'] + '\n' + elements_info['C'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('6'))
        # el.place(x=525, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['N']['Symbol'] + '\n' + elements_info['N'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('7'))
        # el.place(x=565, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['O']['Symbol'] + '\n' + elements_info['O'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('8'))
        # el.place(x=605, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['F']['Symbol'] + '\n' + elements_info['F'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('9'))
        # el.place(x=645, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['Ne']['Symbol'] + '\n' + elements_info['Ne'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('10'))
        # el.place(x=685, y=140)
        # el = ttk.Button(self.parent, text=(elements_info['Na']['Symbol'] + '\n' + elements_info['Na'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('11'))
        # el.place(x=5, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['Mg']['Symbol'] + '\n' + elements_info['Mg'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('12'))
        # el.place(x=45, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['Al']['Symbol'] + '\n' + elements_info['Al'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('13'))
        # el.place(x=485, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['Si']['Symbol'] + '\n' + elements_info['Si'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('14'))
        # el.place(x=525, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['P']['Symbol'] + '\n' + elements_info['P'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('15'))
        # el.place(x=565, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['S']['Symbol'] + '\n' + elements_info['S'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('16'))
        # el.place(x=605, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['Cl']['Symbol'] + '\n' + elements_info['Cl'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('17'))
        # el.place(x=645, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['Ar']['Symbol'] + '\n' + elements_info['Ar'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('18'))
        # el.place(x=685, y=180)
        # el = ttk.Button(self.parent, text=(elements_info['K']['Symbol'] + '\n' + elements_info['K'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('19'))
        # el.place(x=5, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Ca']['Symbol'] + '\n' + elements_info['Ca'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('20'))
        # el.place(x=45, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Sc']['Symbol'] + '\n' + elements_info['Sc'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('21'))
        # el.place(x=85, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Ti']['Symbol'] + '\n' + elements_info['Ti'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('22'))
        # el.place(x=125, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['V']['Symbol'] + '\n' + elements_info['V'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('23'))
        # el.place(x=165, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Cr']['Symbol'] + '\n' + elements_info['Cr'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('24'))
        # el.place(x=205, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Mn']['Symbol'] + '\n' + elements_info['Mn'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('25'))
        # el.place(x=245, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Fe']['Symbol'] + '\n' + elements_info['Fe'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('26'))
        # el.place(x=285, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Co']['Symbol'] + '\n' + elements_info['Co'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('27'))
        # el.place(x=325, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Ni']['Symbol'] + '\n' + elements_info['Ni'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('28'))
        # el.place(x=365, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Cu']['Symbol'] + '\n' + elements_info['Cu'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('29'))
        # el.place(x=405, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Zn']['Symbol'] + '\n' + elements_info['Zn'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('30'))
        # el.place(x=445, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Ga']['Symbol'] + '\n' + elements_info['Ga'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('31'))
        # el.place(x=485, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Ge']['Symbol'] + '\n' + elements_info['Ge'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('32'))
        # el.place(x=525, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['As']['Symbol'] + '\n' + elements_info['As'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('33'))
        # el.place(x=565, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Se']['Symbol'] + '\n' + elements_info['Se'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('34'))
        # el.place(x=605, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Br']['Symbol'] + '\n' + elements_info['Br'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('35'))
        # el.place(x=645, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Kr']['Symbol'] + '\n' + elements_info['Kr'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('36'))
        # el.place(x=685, y=220)
        # el = ttk.Button(self.parent, text=(elements_info['Rb']['Symbol'] + '\n' + elements_info['Rb'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('37'))
        # el.place(x=5, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Sr']['Symbol'] + '\n' + elements_info['Sr'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('38'))
        # el.place(x=45, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Y']['Symbol'] + '\n' + elements_info['Y'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('39'))
        # el.place(x=85, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Zr']['Symbol'] + '\n' + elements_info['Zr'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('40'))
        # el.place(x=125, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Nb']['Symbol'] + '\n' + elements_info['Nb'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('41'))
        # el.place(x=165, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Mo']['Symbol'] + '\n' + elements_info['Mo'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('42'))
        # el.place(x=205, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Tc']['Symbol'] + '\n' + elements_info['Tc'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('43'))
        # el.place(x=245, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Ru']['Symbol'] + '\n' + elements_info['Ru'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('44'))
        # el.place(x=285, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Rh']['Symbol'] + '\n' + elements_info['Rh'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('45'))
        # el.place(x=325, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Pd']['Symbol'] + '\n' + elements_info['Pd'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('46'))
        # el.place(x=365, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Ag']['Symbol'] + '\n' + elements_info['Ag'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('47'))
        # el.place(x=405, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Cd']['Symbol'] + '\n' + elements_info['Cd'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('48'))
        # el.place(x=445, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['In']['Symbol'] + '\n' + elements_info['In'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('49'))
        # el.place(x=485, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Sn']['Symbol'] + '\n' + elements_info['Sn'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('50'))
        # el.place(x=525, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Sb']['Symbol'] + '\n' + elements_info['Sb'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('51'))
        # el.place(x=565, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Te']['Symbol'] + '\n' + elements_info['Te'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('52'))
        # el.place(x=605, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['I']['Symbol'] + '\n' + elements_info['I'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('53'))
        # el.place(x=645, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Xe']['Symbol'] + '\n' + elements_info['Xe'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('54'))
        # el.place(x=685, y=260)
        # el = ttk.Button(self.parent, text=(elements_info['Cs']['Symbol'] + '\n' + elements_info['Cs'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('55'))
        # el.place(x=5, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Ba']['Symbol'] + '\n' + elements_info['Ba'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('56'))
        # el.place(x=45, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['La']['Symbol'] + '\n' + elements_info['La'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('57'))
        # el.place(x=85, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['La']['Symbol'] + '\n' + elements_info['La'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('57'))
        # el.place(x=125, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Ce']['Symbol'] + '\n' + elements_info['Ce'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('58'))
        # el.place(x=165, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Pr']['Symbol'] + '\n' + elements_info['Pr'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('59'))
        # el.place(x=205, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Nd']['Symbol'] + '\n' + elements_info['Nd'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('60'))
        # el.place(x=245, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Pm']['Symbol'] + '\n' + elements_info['Pm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('61'))
        # el.place(x=285, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Sm']['Symbol'] + '\n' + elements_info['Sm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('62'))
        # el.place(x=325, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Eu']['Symbol'] + '\n' + elements_info['Eu'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('63'))
        # el.place(x=365, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Gd']['Symbol'] + '\n' + elements_info['Gd'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('64'))
        # el.place(x=405, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Tb']['Symbol'] + '\n' + elements_info['Tb'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('65'))
        # el.place(x=445, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Dy']['Symbol'] + '\n' + elements_info['Dy'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('66'))
        # el.place(x=485, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Ho']['Symbol'] + '\n' + elements_info['Ho'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('67'))
        # el.place(x=525, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Er']['Symbol'] + '\n' + elements_info['Er'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('68'))
        # el.place(x=565, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Tm']['Symbol'] + '\n' + elements_info['Tm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('69'))
        # el.place(x=605, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Yb']['Symbol'] + '\n' + elements_info['Yb'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('70'))
        # el.place(x=645, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Lu']['Symbol'] + '\n' + elements_info['Lu'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('71'))
        # el.place(x=685, y=420)
        # el = ttk.Button(self.parent, text=(elements_info['Hf']['Symbol'] + '\n' + elements_info['Hf'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('72'))
        # el.place(x=125, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Ta']['Symbol'] + '\n' + elements_info['Ta'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('73'))
        # el.place(x=165, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['W']['Symbol'] + '\n' + elements_info['W'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('74'))
        # el.place(x=205, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Re']['Symbol'] + '\n' + elements_info['Re'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('75'))
        # el.place(x=245, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Os']['Symbol'] + '\n' + elements_info['Os'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('76'))
        # el.place(x=285, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Ir']['Symbol'] + '\n' + elements_info['Ir'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('77'))
        # el.place(x=325, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Pt']['Symbol'] + '\n' + elements_info['Pt'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('78'))
        # el.place(x=365, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Au']['Symbol'] + '\n' + elements_info['Au'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('79'))
        # el.place(x=405, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Hg']['Symbol'] + '\n' + elements_info['Hg'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('80'))
        # el.place(x=445, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Ti']['Symbol'] + '\n' + elements_info['Ti'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('81'))
        # el.place(x=485, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Pb']['Symbol'] + '\n' + elements_info['Pb'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('82'))
        # el.place(x=525, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Bi']['Symbol'] + '\n' + elements_info['Bi'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('83'))
        # el.place(x=565, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Po']['Symbol'] + '\n' + elements_info['Po'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('84'))
        # el.place(x=605, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['At']['Symbol'] + '\n' + elements_info['At'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('85'))
        # el.place(x=645, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Rn']['Symbol'] + '\n' + elements_info['Rn'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('86'))
        # el.place(x=685, y=300)
        # el = ttk.Button(self.parent, text=(elements_info['Fr']['Symbol'] + '\n' + elements_info['Fr'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('87'))
        # el.place(x=5, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Ra']['Symbol'] + '\n' + elements_info['Ra'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('88'))
        # el.place(x=45, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Ac']['Symbol'] + '\n' + elements_info['Ac'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('89'))
        # el.place(x=85, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Ac']['Symbol'] + '\n' + elements_info['Ac'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('89'))
        # el.place(x=125, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Th']['Symbol'] + '\n' + elements_info['Th'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('90'))
        # el.place(x=165, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Pa']['Symbol'] + '\n' + elements_info['Pa'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('91'))
        # el.place(x=205, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['U']['Symbol'] + '\n' + elements_info['U'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('92'))
        # el.place(x=245, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Np']['Symbol'] + '\n' + elements_info['Np'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('93'))
        # el.place(x=285, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Pu']['Symbol'] + '\n' + elements_info['Pu'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('94'))
        # el.place(x=325, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Am']['Symbol'] + '\n' + elements_info['Am'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('95'))
        # el.place(x=365, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Cm']['Symbol'] + '\n' + elements_info['Cm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('96'))
        # el.place(x=405, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Bk']['Symbol'] + '\n' + elements_info['Bk'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('97'))
        # el.place(x=445, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Cf']['Symbol'] + '\n' + elements_info['Cf'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('98'))
        # el.place(x=485, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Es']['Symbol'] + '\n' + elements_info['Es'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('99'))
        # el.place(x=525, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Fm']['Symbol'] + '\n' + elements_info['Fm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('100'))
        # el.place(x=565, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Md']['Symbol'] + '\n' + elements_info['Md'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('101'))
        # el.place(x=605, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['No']['Symbol'] + '\n' + elements_info['No'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('102'))
        # el.place(x=645, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Lr']['Symbol'] + '\n' + elements_info['Lr'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('103'))
        # el.place(x=685, y=460)
        # el = ttk.Button(self.parent, text=(elements_info['Rf']['Symbol'] + '\n' + elements_info['Rf'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('104'))
        # el.place(x=125, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Db']['Symbol'] + '\n' + elements_info['Db'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('105'))
        # el.place(x=165, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Sg']['Symbol'] + '\n' + elements_info['Sg'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('106'))
        # el.place(x=205, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Bh']['Symbol'] + '\n' + elements_info['Bh'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('107'))
        # el.place(x=245, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Hs']['Symbol'] + '\n' + elements_info['Hs'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('108'))
        # el.place(x=285, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Mt']['Symbol'] + '\n' + elements_info['Mt'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('109'))
        # el.place(x=325, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Ds']['Symbol'] + '\n' + elements_info['Ds'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('110'))
        # el.place(x=365, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Rg']['Symbol'] + '\n' + elements_info['Rg'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('111'))
        # el.place(x=405, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Cn']['Symbol'] + '\n' + elements_info['Cn'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('112'))
        # el.place(x=445, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Nh']['Symbol'] + '\n' + elements_info['Nh'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('113'))
        # el.place(x=485, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Fl']['Symbol'] + '\n' + elements_info['Fl'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('114'))
        # el.place(x=525, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Mc']['Symbol'] + '\n' + elements_info['Mc'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('115'))
        # el.place(x=565, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Lv']['Symbol'] + '\n' + elements_info['Lv'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('116'))
        # el.place(x=605, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Ts']['Symbol'] + '\n' + elements_info['Ts'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('117'))
        # el.place(x=645, y=340)
        # el = ttk.Button(self.parent, text=(elements_info['Og']['Symbol'] + '\n' + elements_info['Og'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('118'))
        # el.place(x=685, y=340)


    def configure_styles(self):
        stylee = ttk.Style()
        stylee.configure('e.TButton', background='#0E8A00',
                         foreground='black', width=3)
        styley = ttk.Style()
        styley.configure('y.TButton', background='#9B870C',
                         foreground='black', width=3)
        styleo = ttk.Style()
        styleo.configure('o.TButton', background='#ff8c00',
                         foreground='black', width=3)
        stylep = ttk.Style()
        stylep.configure('p.TButton', background='#e75480',
                         foreground='black', width=3)

    def get_element_text(self, element_position):
        return elements_info[element_position['symbol']]['Symbol'] + '\n' + elements_info[element_position['symbol']][self.active_property]

    def set_active_property(self, active_property):
        self.active_property = active_property
        for index, element_position in enumerate(elements_position):
            self.elements[index].configure(
                text=self.get_element_text(element_position))

    def create_command(self, symbol):
        return lambda: self.search_symbol(symbol)
