import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
from tkinter import filedialog

import utils.search as search
from data.elements_info import elements_info


class Periodic(tk.Frame):

    def __init__(self, parent):
        self.parent = parent
        self.elements_info = elements_info
        self.active_property = 'Atomic Number'
        self.search = search.Search(self.parent)
        self.search_atomic_number = self.search.search_atomic_number
        self.create_periodic_tab()

    def create_periodic_tab(self):
        theme1 = tk.PhotoImage(file='assets/theme.png')
        them1 = tk.Label(self.parent,image=theme1)
        them1.place(x=50, y=0)
        them1.image = theme1
        
        stylee = ttk.Style(self.parent)
        stylee.configure('e.TButton', background='#0E8A00', foreground='#0E8A00', width=5)
        styley = ttk.Style(self.parent)
        styley.configure('y.TButton', background='#9B870C', foreground='#9B870C', width=5)
        styleo = ttk.Style(self.parent)
        styleo.configure('o.TButton', background='#ff8c00', foreground='#ff8c00', width=5)
        stylep = ttk.Style(self.parent)
        stylep.configure('p.TButton', background='#e75480', foreground='#e75480', width=5)

        el = ttk.Button(self.parent, text=(self.elements_info['H']['Symbol'] + '\n' + self.elements_info['H'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('1'))
        el.place(x=5,y=100)
        el = ttk.Button(self.parent, text=(self.elements_info['He']['Symbol'] + '\n' + self.elements_info['He'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('2'))
        el.place(x=685, y=100)
        el = ttk.Button(self.parent, text=(self.elements_info['Li']['Symbol'] + '\n' + self.elements_info['Li'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('3'))
        el.place(x=5, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['Be']['Symbol'] + '\n' + self.elements_info['Be'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('4'))
        el.place(x=45, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['B']['Symbol'] + '\n' + self.elements_info['B'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('5'))
        el.place(x=485, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['C']['Symbol'] + '\n' + self.elements_info['C'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('6'))
        el.place(x=525, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['N']['Symbol'] + '\n' + self.elements_info['N'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('7'))
        el.place(x=565, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['O']['Symbol'] + '\n' + self.elements_info['O'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('8'))
        el.place(x=605, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['F']['Symbol'] + '\n' + self.elements_info['F'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('9'))
        el.place(x=645, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['Ne']['Symbol'] + '\n' + self.elements_info['Ne'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('10'))
        el.place(x=685, y=140)
        el = ttk.Button(self.parent, text=(self.elements_info['Na']['Symbol'] + '\n' + self.elements_info['Na'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('11'))
        el.place(x=5, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['Mg']['Symbol'] + '\n' + self.elements_info['Mg'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('12'))
        el.place(x=45, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['Al']['Symbol'] + '\n' + self.elements_info['Al'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('13'))
        el.place(x=485, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['Si']['Symbol'] + '\n' + self.elements_info['Si'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('14'))
        el.place(x=525, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['P']['Symbol'] + '\n' + self.elements_info['P'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('15'))
        el.place(x=565, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['S']['Symbol'] + '\n' + self.elements_info['S'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('16'))
        el.place(x=605, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['Cl']['Symbol'] + '\n' + self.elements_info['Cl'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('17'))
        el.place(x=645, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['Ar']['Symbol'] + '\n' + self.elements_info['Ar'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('18'))
        el.place(x=685, y=180)
        el = ttk.Button(self.parent, text=(self.elements_info['K']['Symbol'] + '\n' + self.elements_info['K'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('19'))
        el.place(x=5, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Ca']['Symbol'] + '\n' + self.elements_info['Ca'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('20'))
        el.place(x=45, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Sc']['Symbol'] + '\n' + self.elements_info['Sc'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('21'))
        el.place(x=85, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Ti']['Symbol'] + '\n' + self.elements_info['Ti'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('22'))
        el.place(x=125, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['V']['Symbol'] + '\n' + self.elements_info['V'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('23'))
        el.place(x=165, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Cr']['Symbol'] + '\n' + self.elements_info['Cr'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('24'))
        el.place(x=205, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Mn']['Symbol'] + '\n' + self.elements_info['Mn'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('25'))
        el.place(x=245, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Fe']['Symbol'] + '\n' + self.elements_info['Fe'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('26'))
        el.place(x=285, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Co']['Symbol'] + '\n' + self.elements_info['Co'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('27'))
        el.place(x=325, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Ni']['Symbol'] + '\n' + self.elements_info['Ni'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('28'))
        el.place(x=365, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Cu']['Symbol'] + '\n' + self.elements_info['Cu'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('29'))
        el.place(x=405, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Zn']['Symbol'] + '\n' + self.elements_info['Zn'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('30'))
        el.place(x=445, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Ga']['Symbol'] + '\n' + self.elements_info['Ga'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('31'))
        el.place(x=485, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Ge']['Symbol'] + '\n' + self.elements_info['Ge'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('32'))
        el.place(x=525, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['As']['Symbol'] + '\n' + self.elements_info['As'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('33'))
        el.place(x=565, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Se']['Symbol'] + '\n' + self.elements_info['Se'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('34'))
        el.place(x=605, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Br']['Symbol'] + '\n' + self.elements_info['Br'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('35'))
        el.place(x=645, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Kr']['Symbol'] + '\n' + self.elements_info['Kr'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('36'))
        el.place(x=685, y=220)
        el = ttk.Button(self.parent, text=(self.elements_info['Rb']['Symbol'] + '\n' + self.elements_info['Rb'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('37'))
        el.place(x=5, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Sr']['Symbol'] + '\n' + self.elements_info['Sr'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('38'))
        el.place(x=45, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Y']['Symbol'] + '\n' + self.elements_info['Y'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('39'))
        el.place(x=85, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Zr']['Symbol'] + '\n' + self.elements_info['Zr'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('40'))
        el.place(x=125, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Nb']['Symbol'] + '\n' + self.elements_info['Nb'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('41'))
        el.place(x=165, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Mo']['Symbol'] + '\n' + self.elements_info['Mo'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('42'))
        el.place(x=205, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Tc']['Symbol'] + '\n' + self.elements_info['Tc'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('43'))
        el.place(x=245, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Ru']['Symbol'] + '\n' + self.elements_info['Ru'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('44'))
        el.place(x=285, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Rh']['Symbol'] + '\n' + self.elements_info['Rh'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('45'))
        el.place(x=325, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Pd']['Symbol'] + '\n' + self.elements_info['Pd'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('46'))
        el.place(x=365, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Ag']['Symbol'] + '\n' + self.elements_info['Ag'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('47'))
        el.place(x=405, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Cd']['Symbol'] + '\n' + self.elements_info['Cd'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('48'))
        el.place(x=445, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['In']['Symbol'] + '\n' + self.elements_info['In'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('49'))
        el.place(x=485, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Sn']['Symbol'] + '\n' + self.elements_info['Sn'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('50'))
        el.place(x=525, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Sb']['Symbol'] + '\n' + self.elements_info['Sb'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('51'))
        el.place(x=565, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Te']['Symbol'] + '\n' + self.elements_info['Te'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('52'))
        el.place(x=605, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['I']['Symbol'] + '\n' + self.elements_info['I'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('53'))
        el.place(x=645, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Xe']['Symbol'] + '\n' + self.elements_info['Xe'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('54'))
        el.place(x=685, y=260)
        el = ttk.Button(self.parent, text=(self.elements_info['Cs']['Symbol'] + '\n' + self.elements_info['Cs'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('55'))
        el.place(x=5, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Ba']['Symbol'] + '\n' + self.elements_info['Ba'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('56'))
        el.place(x=45, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['La']['Symbol'] + '\n' + self.elements_info['La'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('57'))
        el.place(x=85, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['La']['Symbol'] + '\n' + self.elements_info['La'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('57'))
        el.place(x=125, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Ce']['Symbol'] + '\n' + self.elements_info['Ce'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('58'))
        el.place(x=165, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Pr']['Symbol'] + '\n' + self.elements_info['Pr'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('59'))
        el.place(x=205, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Nd']['Symbol'] + '\n' + self.elements_info['Nd'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('60'))
        el.place(x=245, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Pm']['Symbol'] + '\n' + self.elements_info['Pm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('61'))
        el.place(x=285, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Sm']['Symbol'] + '\n' + self.elements_info['Sm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('62'))
        el.place(x=325, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Eu']['Symbol'] + '\n' + self.elements_info['Eu'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('63'))
        el.place(x=365, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Gd']['Symbol'] + '\n' + self.elements_info['Gd'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('64'))
        el.place(x=405, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Tb']['Symbol'] + '\n' + self.elements_info['Tb'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('65'))
        el.place(x=445, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Dy']['Symbol'] + '\n' + self.elements_info['Dy'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('66'))
        el.place(x=485, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Ho']['Symbol'] + '\n' + self.elements_info['Ho'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('67'))
        el.place(x=525, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Er']['Symbol'] + '\n' + self.elements_info['Er'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('68'))
        el.place(x=565, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Tm']['Symbol'] + '\n' + self.elements_info['Tm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('69'))
        el.place(x=605, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Yb']['Symbol'] + '\n' + self.elements_info['Yb'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('70'))
        el.place(x=645, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Lu']['Symbol'] + '\n' + self.elements_info['Lu'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('71'))
        el.place(x=685, y=420)
        el = ttk.Button(self.parent, text=(self.elements_info['Hf']['Symbol'] + '\n' + self.elements_info['Hf'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('72'))
        el.place(x=125, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Ta']['Symbol'] + '\n' + self.elements_info['Ta'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('73'))
        el.place(x=165, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['W']['Symbol'] + '\n' + self.elements_info['W'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('74'))
        el.place(x=205, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Re']['Symbol'] + '\n' + self.elements_info['Re'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('75'))
        el.place(x=245, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Os']['Symbol'] + '\n' + self.elements_info['Os'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('76'))
        el.place(x=285, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Ir']['Symbol'] + '\n' + self.elements_info['Ir'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('77'))
        el.place(x=325, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Pt']['Symbol'] + '\n' + self.elements_info['Pt'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('78'))
        el.place(x=365, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Au']['Symbol'] + '\n' + self.elements_info['Au'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('79'))
        el.place(x=405, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Hg']['Symbol'] + '\n' + self.elements_info['Hg'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('80'))
        el.place(x=445, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Ti']['Symbol'] + '\n' + self.elements_info['Ti'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('81'))
        el.place(x=485, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Pb']['Symbol'] + '\n' + self.elements_info['Pb'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('82'))
        el.place(x=525, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Bi']['Symbol'] + '\n' + self.elements_info['Bi'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('83'))
        el.place(x=565, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Po']['Symbol'] + '\n' + self.elements_info['Po'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('84'))
        el.place(x=605, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['At']['Symbol'] + '\n' + self.elements_info['At'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('85'))
        el.place(x=645, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Rn']['Symbol'] + '\n' + self.elements_info['Rn'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('86'))
        el.place(x=685, y=300)
        el = ttk.Button(self.parent, text=(self.elements_info['Fr']['Symbol'] + '\n' + self.elements_info['Fr'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('87'))
        el.place(x=5, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Ra']['Symbol'] + '\n' + self.elements_info['Ra'][self.active_property]), style='p.TButton', command=lambda: self.search_atomic_number('88'))
        el.place(x=45, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Ac']['Symbol'] + '\n' + self.elements_info['Ac'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('89'))
        el.place(x=85, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Ac']['Symbol'] + '\n' + self.elements_info['Ac'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('89'))
        el.place(x=125, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Th']['Symbol'] + '\n' + self.elements_info['Th'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('90'))
        el.place(x=165, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Pa']['Symbol'] + '\n' + self.elements_info['Pa'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('91'))
        el.place(x=205, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['U']['Symbol'] + '\n' + self.elements_info['U'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('92'))
        el.place(x=245, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Np']['Symbol'] + '\n' + self.elements_info['Np'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('93'))
        el.place(x=285, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Pu']['Symbol'] + '\n' + self.elements_info['Pu'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('94'))
        el.place(x=325, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Am']['Symbol'] + '\n' + self.elements_info['Am'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('95'))
        el.place(x=365, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Cm']['Symbol'] + '\n' + self.elements_info['Cm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('96'))
        el.place(x=405, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Bk']['Symbol'] + '\n' + self.elements_info['Bk'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('97'))
        el.place(x=445, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Cf']['Symbol'] + '\n' + self.elements_info['Cf'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('98'))
        el.place(x=485, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Es']['Symbol'] + '\n' + self.elements_info['Es'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('99'))
        el.place(x=525, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Fm']['Symbol'] + '\n' + self.elements_info['Fm'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('100'))
        el.place(x=565, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Md']['Symbol'] + '\n' + self.elements_info['Md'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('101'))
        el.place(x=605, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['No']['Symbol'] + '\n' + self.elements_info['No'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('102'))
        el.place(x=645, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Lr']['Symbol'] + '\n' + self.elements_info['Lr'][self.active_property]), style='e.TButton', command=lambda: self.search_atomic_number('103'))
        el.place(x=685, y=460)
        el = ttk.Button(self.parent, text=(self.elements_info['Rf']['Symbol'] + '\n' + self.elements_info['Rf'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('104'))
        el.place(x=125, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Db']['Symbol'] + '\n' + self.elements_info['Db'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('105'))
        el.place(x=165, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Sg']['Symbol'] + '\n' + self.elements_info['Sg'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('106'))
        el.place(x=205, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Bh']['Symbol'] + '\n' + self.elements_info['Bh'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('107'))
        el.place(x=245, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Hs']['Symbol'] + '\n' + self.elements_info['Hs'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('108'))
        el.place(x=285, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Mt']['Symbol'] + '\n' + self.elements_info['Mt'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('109'))
        el.place(x=325, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Ds']['Symbol'] + '\n' + self.elements_info['Ds'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('110'))
        el.place(x=365, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Rg']['Symbol'] + '\n' + self.elements_info['Rg'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('111'))
        el.place(x=405, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Cn']['Symbol'] + '\n' + self.elements_info['Cn'][self.active_property]), style='y.TButton', command=lambda: self.search_atomic_number('112'))
        el.place(x=445, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Nh']['Symbol'] + '\n' + self.elements_info['Nh'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('113'))
        el.place(x=485, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Fl']['Symbol'] + '\n' + self.elements_info['Fl'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('114'))
        el.place(x=525, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Mc']['Symbol'] + '\n' + self.elements_info['Mc'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('115'))
        el.place(x=565, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Lv']['Symbol'] + '\n' + self.elements_info['Lv'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('116'))
        el.place(x=605, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Ts']['Symbol'] + '\n' + self.elements_info['Ts'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('117'))
        el.place(x=645, y=340)
        el = ttk.Button(self.parent, text=(self.elements_info['Og']['Symbol'] + '\n' + self.elements_info['Og'][self.active_property]), style='o.TButton', command=lambda: self.search_atomic_number('118'))
        el.place(x=685, y=340)
        
        atmb = ttk.Button(self.parent, text='''Atomic\nNumber''',command=lambda: self.set_active_property('Atomic Number'))
        atmb.place(x=5,y=557,width=73)
        msnb = ttk.Button(self.parent, text='''Atomic\nMass''',command=lambda: self.set_active_property('Atomic Mass'))
        msnb.place(x=77,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Phase\n ''',command=lambda: self.set_active_property('Phase'))
        atmb.place(x=149,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Boiling\nPoint''',command=lambda: self.set_active_property('Boiling Point'))
        atmb.place(x=221,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Melting\nPoint''',command=lambda: self.set_active_property('Melting Point'))
        atmb.place(x=293,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Electro\nNegativity''',command=lambda: self.set_active_property('Electronegativity'))
        atmb.place(x=365,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Electron\nAffinity''',command=lambda: self.set_active_property('Electron Affinity'))
        atmb.place(x=437,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Ionization\nEnergy''',command=lambda: self.set_active_property('Ionization Energy'))
        atmb.place(x=509,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Atomic\nRadius''',command=lambda: self.set_active_property('Atomic Radius'))
        atmb.place(x=581,y=557,width=73)
        atmb = ttk.Button(self.parent, text='''Cvelent\nRadius''',command=lambda: self.set_active_property('Covalent Radius'))
        atmb.place(x=653,y=557,width=73)
    
    def set_active_property(self, property):
        self.active_property = property
        
        self.create_periodic_tab()